### PR TITLE
Tiny refactor for the about page.

### PR DESCRIPTION
**Pull request by poshboytl**
we can use a site controller here to handle all kinds for these things like  'about', 'terms', 'licence'等...

### CODE REVIEW

**Comment by poshboytl** [comment]
oh my bad... 我测试没有移动... seconds...

**Comment by poshboytl** [comment]
测试过了.

@winsonwq please help review and merge if there is not problem. :smile:

**Comment by winsonwq** [comment]
我看了，没有问题，我来merge吧，试试。

**Comment by winsonwq** [comment]
Shall we delete this branch?

**Pull request merged**
